package org.cn.kaito.auth.Service;

import org.cn.kaito.auth.Exception.CustomerException;

public interface EntrustService {

    void takeBackEntrust(int entrustID) ;
}
